#!/usr/bin/env node

/**
 * Dependencies.
 */
var app = require('../app');

/**
 * Set the port for the server
 */
app.set('port', process.env.PORT || '3000');
/**
 * Set the  key for the token
 */
//app.set('token_v1', '14haCks7Via99xteRn00FOrIPS');

/**
 * Set the server to listen on the set port
 */
app.listen(app.get('port'), function(){
    console.log("API by HacksViaXtern\n***API running on port:"+app.get('port')+"***"+app.get('token_v1'));
});